apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go
  labels:
    app: my-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-go
  template:
    metadata:
      labels:
        app: my-go
    spec:
      containers:
      - name: my-go
        image: my-go:4
        ports:
        - containerPort: 80